// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250305064153_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domains.ApplicantDomain.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CitizenshipByBirth")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNonResident")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceOfWorkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaceOfWorkId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("Domains.ApplicantDomain.PlaceOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("PlaceOfWork");
                });

            modelBuilder.Entity("Domains.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domains.VisaApplicationDomain.VisaApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("character varying(70)");

                    b.Property<bool>("ForGroup")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedNumberOfEntries")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ValidDaysRequested")
                        .HasColumnType("integer");

                    b.Property<int>("VisaCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("VisaApplication");
                });

            modelBuilder.Entity("Domains.ApplicantDomain.Applicant", b =>
                {
                    b.HasOne("Domains.ApplicantDomain.PlaceOfWork", "PlaceOfWork")
                        .WithMany()
                        .HasForeignKey("PlaceOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Domains.ApplicantDomain.Applicant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domains.ApplicantDomain.Name", "FatherName", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicant");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("Domains.ApplicantDomain.Name", "MotherName", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicant");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("Domains.ApplicantDomain.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicant");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("Domains.ApplicantDomain.Passport", "Passport", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("IssueDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Issuer")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicant");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.Navigation("FatherName")
                        .IsRequired();

                    b.Navigation("MotherName")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Passport")
                        .IsRequired();

                    b.Navigation("PlaceOfWork");
                });

            modelBuilder.Entity("Domains.ApplicantDomain.PlaceOfWork", b =>
                {
                    b.OwnsOne("Domains.ApplicantDomain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PlaceOfWorkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Building")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(70)
                                .IsUnicode(false)
                                .HasColumnType("character varying(70)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(70)
                                .IsUnicode(false)
                                .HasColumnType("character varying(70)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PlaceOfWorkId");

                            b1.ToTable("PlaceOfWork");

                            b1.WithOwner()
                                .HasForeignKey("PlaceOfWorkId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.VisaApplicationDomain.VisaApplication", b =>
                {
                    b.HasOne("Domains.ApplicantDomain.Applicant", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domains.VisaApplicationDomain.PastVisa", "PastVisas", b1 =>
                        {
                            b1.Property<Guid>("VisaApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("IssueDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(70)
                                .IsUnicode(false)
                                .HasColumnType("character varying(70)");

                            b1.HasKey("VisaApplicationId", "Id");

                            b1.ToTable("PastVisa");

                            b1.WithOwner()
                                .HasForeignKey("VisaApplicationId");
                        });

                    b.OwnsMany("Domains.VisaApplicationDomain.PastVisit", "PastVisits", b1 =>
                        {
                            b1.Property<Guid>("VisaApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DestinationCountry")
                                .IsRequired()
                                .HasMaxLength(70)
                                .IsUnicode(false)
                                .HasColumnType("character varying(70)");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VisaApplicationId", "Id");

                            b1.ToTable("PastVisit");

                            b1.WithOwner()
                                .HasForeignKey("VisaApplicationId");
                        });

                    b.OwnsOne("Domains.VisaApplicationDomain.PermissionToDestCountry", "PermissionToDestCountry", b1 =>
                        {
                            b1.Property<Guid>("VisaApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Issuer")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("VisaApplicationId");

                            b1.ToTable("VisaApplication");

                            b1.WithOwner()
                                .HasForeignKey("VisaApplicationId");
                        });

                    b.OwnsOne("Domains.VisaApplicationDomain.ReentryPermit", "ReentryPermit", b1 =>
                        {
                            b1.Property<Guid>("VisaApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(25)
                                .IsUnicode(false)
                                .HasColumnType("character varying(25)");

                            b1.HasKey("VisaApplicationId");

                            b1.ToTable("VisaApplication");

                            b1.WithOwner()
                                .HasForeignKey("VisaApplicationId");
                        });

                    b.Navigation("PastVisas");

                    b.Navigation("PastVisits");

                    b.Navigation("PermissionToDestCountry");

                    b.Navigation("ReentryPermit");
                });
#pragma warning restore 612, 618
        }
    }
}
