using ApplicationLayer.GeneralNeededServices;
using Domains.VisaApplicationDomain;

namespace ApplicationLayer.DataAccessingServices.VisaApplications.NeededServices;

public interface IVisaApplicationsRepository : IGenericRepository<VisaApplication>;